#!/usr/bin/env python3
"""Appends a draft update section to guides/maf-1.3.0-migration-guide.md.

Reads OLD_VERSION, NEW_VERSION from environment variables.
Called by .github/workflows/maf-release-watcher.yml
"""
import os

old = os.environ.get('OLD_VERSION', 'unknown')
new = os.environ.get('NEW_VERSION', 'unknown')

try:
    with open('diff-core.txt', encoding='utf-8') as f:
        diff = ''.join(f.readlines()[:50])
except Exception:
    diff = 'Diff not available'

try:
    with open('release-notes.txt', encoding='utf-8') as f:
        notes = f.read().strip()
except Exception:
    notes = 'No release notes'

section = (
    "\n\n---\n\n"
    f"## Section AUTO \u2014 Changes in {old} \u2192 {new}\n\n"
    f"<!-- introduced: {new} | applies-to: {old}.x \u2192 {new}.x | deprecated-in: none -->\n"
    "<!-- AUTO-GENERATED by maf-release-watcher \u2014 REQUIRES HUMAN REVIEW before merging -->\n\n"
    "> \u26a0\ufe0f This section was auto-generated. Review all content before relying on it for migrations.\n\n"
    "### Diff Summary (from dotnet-inspect)\n\n"
    "```\n"
    + diff
    + "\n```\n\n"
    "### Release Notes Extract\n\n"
    + notes
    + "\n\n"
    "### Breaking Changes (requires human verification)\n\n"
    "<!-- TODO: Review the diff above and list breaking changes here -->\n"
    "- [ ] Review diff output and populate this section\n\n"
    "### New Patterns\n\n"
    "<!-- TODO: Document any new recommended patterns from release notes -->\n"
    "- [ ] Review release notes and populate this section\n\n"
    "### Obsolete APIs Added\n\n"
    "<!-- TODO: Run dotnet build against new version and check CS0618 output -->\n"
    "- [ ] Run cs0618-hunter against new version and document findings here\n\n"
    "### Known Misalignments\n\n"
    "<!-- TODO: Document any discrepancies between official docs and assembly behavior -->\n"
    "- [ ] Update after migration testing\n"
)

guide_path = 'guides/maf-1.3.0-migration-guide.md'
with open(guide_path, 'a', encoding='utf-8') as f:
    f.write(section)

print(f"Draft guide section appended to {guide_path}")
