using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace MafAutopilot;

/// <summary>
/// CLI init subcommand: `maf-autopilot init`
///
/// Configures a target repository for MAF migration:
///   1. Writes (or merges) .vscode/mcp.json with the maf-autopilot global-tool server entry.
///   2. Creates .github/copilot-instructions.md (MAF hard constraints) — only if it doesn't exist.
///
/// Run from the root of the repository you want to configure:
///   cd /path/to/your-repo
///   maf-autopilot init
/// </summary>
internal static class InitCommand
{
    private static readonly Assembly _asm = typeof(InitCommand).Assembly;

    public static async Task<int> RunAsync()
    {
        var targetDir = Directory.GetCurrentDirectory();

        Console.WriteLine("maf-autopilot init");
        Console.WriteLine($"  Configuring: {targetDir}");
        Console.WriteLine();

        await WriteMcpJsonAsync(targetDir);
        await WriteCopilotInstructionsAsync(targetDir);

        Console.WriteLine();
        Console.WriteLine("Done. Open this folder in VS Code, then in Copilot Chat:");
        Console.WriteLine("  /maf-audit     — scan the codebase and generate a migration plan");
        Console.WriteLine("  /maf-migrate   — execute tasks from your migration plan");
        Console.WriteLine("  /maf-cs0618-hunt — find and fix all obsolete API warnings");
        Console.WriteLine();
        Console.WriteLine("Full guide: read maf://guide");
        Console.WriteLine("Constraint rules: read maf://constraints");

        return 0;
    }

    // ------------------------------------------------------------------ //
    //  .vscode/mcp.json                                                    //
    // ------------------------------------------------------------------ //

    private static async Task WriteMcpJsonAsync(string targetDir)
    {
        var vscodeDir = Path.Combine(targetDir, ".vscode");
        var mcpJsonPath = Path.Combine(vscodeDir, "mcp.json");

        Directory.CreateDirectory(vscodeDir);

        // Read existing file if present; tolerate malformed JSON by starting fresh
        JsonObject root;
        if (File.Exists(mcpJsonPath))
        {
            try
            {
                root = JsonNode.Parse(await File.ReadAllTextAsync(mcpJsonPath))!.AsObject();
            }
            catch
            {
                Console.WriteLine($"  ⚠ .vscode/mcp.json exists but could not be parsed — recreating");
                root = new JsonObject();
            }
        }
        else
        {
            root = new JsonObject();
        }

        if (!root.ContainsKey("servers"))
            root["servers"] = new JsonObject();

        var servers = root["servers"]!.AsObject();

        if (servers.ContainsKey("maf-autopilot"))
        {
            Console.WriteLine("  ✓ .vscode/mcp.json — maf-autopilot entry already present, no change");
            return;
        }

        // Add the global-tool entry (not dotnet run — assumes `dotnet tool install -g maf-autopilot`)
        servers["maf-autopilot"] = new JsonObject
        {
            ["type"] = "stdio",
            ["command"] = "maf-autopilot",
            ["args"] = new JsonArray(),
            ["env"] = new JsonObject()
        };

        var json = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(mcpJsonPath, json + Environment.NewLine);
        Console.WriteLine("  ✓ .vscode/mcp.json — added maf-autopilot global-tool server entry");
    }

    // ------------------------------------------------------------------ //
    //  .github/copilot-instructions.md                                     //
    // ------------------------------------------------------------------ //

    private static async Task WriteCopilotInstructionsAsync(string targetDir)
    {
        var githubDir = Path.Combine(targetDir, ".github");
        var instructionsPath = Path.Combine(githubDir, "copilot-instructions.md");

        if (File.Exists(instructionsPath))
        {
            Console.WriteLine("  ℹ .github/copilot-instructions.md already exists — not overwriting");
            Console.WriteLine("    (Add the constraint rules manually, or delete it and re-run init)");
            return;
        }

        Directory.CreateDirectory(githubDir);

        // Embed the MAF hard constraint rules (stripped of VS Code instructions frontmatter)
        var constraintsRaw = ReadEmbedded("constraints.md");
        var constraintsBody = StripFrontmatter(constraintsRaw).TrimStart();

        var content = new StringBuilder();
        content.AppendLine("# MAF 1.3.0 Migration — Auto-Loaded Constraints");
        content.AppendLine();
        content.AppendLine("> Auto-generated by `maf-autopilot init`. Do not hand-edit.");
        content.AppendLine("> Regenerate: delete this file and re-run `maf-autopilot init`.");
        content.AppendLine("> Authoritative version: read `maf://constraints` in Copilot Chat.");
        content.AppendLine();
        content.Append(constraintsBody);

        await File.WriteAllTextAsync(instructionsPath, content.ToString());
        Console.WriteLine("  ✓ .github/copilot-instructions.md — MAF hard constraints installed");
        Console.WriteLine("    (Auto-loads in every Copilot chat in this workspace)");
    }

    // ------------------------------------------------------------------ //
    //  Helpers                                                             //
    // ------------------------------------------------------------------ //

    /// <summary>Strips YAML frontmatter (--- ... ---) from a markdown string.</summary>
    private static string StripFrontmatter(string content)
    {
        var trimmed = content.TrimStart();
        if (!trimmed.StartsWith("---", StringComparison.Ordinal))
            return content;

        var endMarker = trimmed.IndexOf("\n---", 3, StringComparison.Ordinal);
        if (endMarker < 0)
            return content;

        // Skip past the closing --- and any immediately following newline
        var bodyStart = endMarker + 4; // "\n---".Length
        if (bodyStart < trimmed.Length && trimmed[bodyStart] == '\n')
            bodyStart++;
        if (bodyStart < trimmed.Length && trimmed[bodyStart] == '\r')
            bodyStart++;

        return trimmed[bodyStart..];
    }

    private static string ReadEmbedded(string logicalName)
    {
        using var stream = _asm.GetManifestResourceStream(logicalName)
            ?? throw new InvalidOperationException(
                $"Embedded resource '{logicalName}' not found. " +
                $"Available: {string.Join(", ", _asm.GetManifestResourceNames())}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
