using MafAutopilot.Data;

namespace MafAutopilot.Commands;

/// <summary>
/// CLI: <c>maf-autopilot verify-registry</c>.
///
/// **#5 polish (2026-05-13)** — the verification gate for the AI-fill flow.
/// After GitHub Copilot Coding Agent fills the TODO placeholders in
/// <c>registry.yaml</c>, the PR-triggered workflow
/// <c>.github/workflows/maf-ai-fill-verify.yml</c> runs this command to catch
/// the common failure modes BEFORE the PR is merged.
///
/// **What it checks** (per entry):
/// <list type="bullet">
///   <item><c>fix_description</c> is at least 20 chars (not empty / "TODO").</item>
///   <item><c>example_before</c> is non-empty.</item>
///   <item><c>example_after</c> is non-empty.</item>
///   <item><c>example_before</c> != <c>example_after</c> (a real migration shows a change).</item>
///   <item>Both examples have balanced <c>{}</c> and <c>()</c>.</item>
///   <item><c>guide_section</c> is not the literal "TODO" / "TBD" (use "N/A" if no parallel).</item>
/// </list>
///
/// **Exit code:** 0 on success; 1 on any verification failure (with per-entry
/// detail emitted to stderr).
///
/// Skipping rule: entries marked <c>applies_to_codebases: "pre-1.0.0"</c> are
/// SKIPPED — they're documentation of historical patterns, not migration
/// targets, so their examples may reference removed types intentionally.
/// </summary>
public static class VerifyRegistryCommand
{
    public static int Run()
    {
        var registry = new RegistryService();
        var issues = new List<string>();
        var skippedHistorical = 0;
        var skippedRawDrafts = 0;

        foreach (var entry in registry.AllEntries)
        {
            // Pre-1.0 entries are historical docs; their examples may
            // reference removed types deliberately. Skip them.
            var marker = entry.AppliesToCodebases?.Trim();
            if (marker?.StartsWith("pre-", StringComparison.OrdinalIgnoreCase) == true)
            {
                skippedHistorical++;
                continue;
            }

            // Raw drafts — entries where EVERY core fillable field is still
            // a placeholder. These are auto-generated by `registry-extract`
            // and queued for Copilot AI-fill. They legitimately exist in
            // the registry pending fill; skip them rather than failing
            // verification.
            if (IsRawDraft(entry))
            {
                skippedRawDrafts++;
                continue;
            }

            CheckEntry(entry, issues);
        }

        if (issues.Count > 0)
        {
            Console.Error.WriteLine($"❌ Registry verification FAILED: {issues.Count} issue(s) across {registry.AllEntries.Count - skippedHistorical - skippedRawDrafts} active entries ({skippedHistorical} pre-1.0.0 + {skippedRawDrafts} raw-draft entries skipped).");
            Console.Error.WriteLine();
            foreach (var issue in issues)
                Console.Error.WriteLine($"  • {issue}");
            Console.Error.WriteLine();
            Console.Error.WriteLine("Fix locally and re-run `maf-autopilot verify-registry`.");
            return 1;
        }

        Console.WriteLine($"✓ Registry verification PASSED: {registry.AllEntries.Count - skippedHistorical - skippedRawDrafts} active entries clean ({skippedHistorical} pre-1.0.0 + {skippedRawDrafts} raw-draft entries skipped).");
        return 0;
    }

    /// <summary>
    /// True when every fillable core field is a TODO/placeholder — the
    /// "auto-generated by `registry-extract`, never AI-filled" state. These
    /// entries are legitimately in the registry pending fill; the verifier
    /// should skip them so it doesn't fail noisily on the watcher's drafts.
    /// </summary>
    internal static bool IsRawDraft(RegistryEntry entry)
    {
        return LooksLikePlaceholder(entry.ObsoleteSignature)
            && LooksLikePlaceholder(entry.ReplacementSignature)
            && LooksLikePlaceholderOrStartsWith(entry.FixDescription, "TODO")
            && entry.ExampleBefore.Contains("// TODO", StringComparison.OrdinalIgnoreCase)
            && entry.ExampleAfter.Contains("// TODO", StringComparison.OrdinalIgnoreCase);
    }

    private static bool LooksLikePlaceholderOrStartsWith(string? s, string prefix)
    {
        if (LooksLikePlaceholder(s)) return true;
        return !string.IsNullOrWhiteSpace(s)
            && s.Trim().StartsWith(prefix, StringComparison.OrdinalIgnoreCase);
    }

    internal static void CheckEntry(RegistryEntry entry, List<string> issues)
    {
        // fix_description must exist and be substantial.
        if (string.IsNullOrWhiteSpace(entry.FixDescription))
            issues.Add($"{entry.Id}: fix_description is empty.");
        else if (entry.FixDescription.Trim().Length < 20)
            issues.Add($"{entry.Id}: fix_description is too short (< 20 chars): \"{entry.FixDescription.Trim()}\"");
        else if (LooksLikePlaceholder(entry.FixDescription))
            issues.Add($"{entry.Id}: fix_description looks like a placeholder (TODO/TBD/...): \"{entry.FixDescription.Trim()}\"");

        // example_before + example_after must exist + differ + balance.
        if (string.IsNullOrWhiteSpace(entry.ExampleBefore))
            issues.Add($"{entry.Id}: example_before is empty.");
        if (string.IsNullOrWhiteSpace(entry.ExampleAfter))
            issues.Add($"{entry.Id}: example_after is empty.");
        if (!string.IsNullOrWhiteSpace(entry.ExampleBefore)
            && !string.IsNullOrWhiteSpace(entry.ExampleAfter)
            && entry.ExampleBefore.Trim() == entry.ExampleAfter.Trim())
        {
            issues.Add($"{entry.Id}: example_before == example_after (no migration shown).");
        }

        // Brace balance — quick syntactic sanity. Roslyn-parsing fragments
        // gives false negatives (parser is forgiving), so we use the cheaper
        // brace-counter as a "did the Copilot Agent leave half a snippet" check.
        if (!string.IsNullOrWhiteSpace(entry.ExampleBefore) && BraceImbalance(entry.ExampleBefore) is var b && b != 0)
            issues.Add($"{entry.Id}: example_before has unbalanced braces (delta = {b}).");
        if (!string.IsNullOrWhiteSpace(entry.ExampleAfter) && BraceImbalance(entry.ExampleAfter) is var a && a != 0)
            issues.Add($"{entry.Id}: example_after has unbalanced braces (delta = {a}).");

        // guide_section must be a number, "N/A", or empty (legacy). Reject
        // explicit placeholders left by the Copilot Agent's filler logic.
        if (LooksLikePlaceholder(entry.GuideSection))
            issues.Add($"{entry.Id}: guide_section is a placeholder (use 'N/A' for no parallel section): \"{entry.GuideSection.Trim()}\"");
    }

    /// <summary>
    /// Returns the count of opening braces minus the count of closing braces,
    /// considering BOTH <c>{}</c> AND <c>()</c>. Zero means balanced.
    /// </summary>
    internal static int BraceImbalance(string source)
    {
        var imbalance = 0;
        foreach (var c in source)
        {
            if (c is '{' or '(') imbalance++;
            else if (c is '}' or ')') imbalance--;
        }
        return imbalance;
    }

    /// <summary>
    /// True if a string looks like an un-filled placeholder.
    /// </summary>
    internal static bool LooksLikePlaceholder(string? s)
    {
        if (string.IsNullOrWhiteSpace(s)) return false;
        var trimmed = s.Trim();
        return trimmed.Equals("TODO", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("TBD", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("XXX", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("TODO:", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("TBD:", StringComparison.OrdinalIgnoreCase);
    }
}
